name: Stopwatch
options:
  bundleIdPrefix: com.stopwatch
  deploymentTarget:
    iOS: "15.0"
targets:
  Stopwatch:
    type: application
    platform: iOS
    sources:
      - path: Stopwatch
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.stopwatch.run
        MARKETING_VERSION: "3.0.6"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_CFBundleDisplayName: Stopwatch
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
        SWIFT_VERSION: "5.0"
